name: Build & Publish Jupyter Book
env:
  POPTUS_PKG:      ${{ github.workspace }}/poptus_pypkg
  GH_ACTIONS_PATH: ${{ github.workspace }}/.github/workflows
  BOOK_HTML_BUILD: ${{ github.workspace }}/book/_build/html
on:
  # TODO: Should this publish for every commit on main or only on release events
  # on main?  If only release events, then the test_book action should also be
  # run on pushes to main that aren't release events.
  push:
    branches: main

jobs:
  # Prefer using the latest Python version supported by the package
  #
  # Since notebooks contain regular and sanity checks, this action not only
  # confirms that the book is building correctly, but also
  # * that notebooks are generating correct content and therefore
  # * that our "Jupyter book test suite" passed.
  build:
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages:    write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source
    # Deploy to github-pages environment
    environment:
      name: github-pages
      url:  ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.14
    - name: Setup Python with tox
      run: $GH_ACTIONS_PATH/setup_tox_github_action.sh ${{ runner.os }}
    - name: Build Jupyter book
      run: |
        pushd $POPTUS_PKG
        tox -r -e book
        popd
    - name: Archive examples Jupyter book 
      uses: actions/upload-pages-artifact@v3
      with:
        path: ${{ env.BOOK_HTML_BUILD}}
    - name: Publish Jupyter book to POptUS's GH page
      id:   deployment
      uses: actions/deploy-pages@v4
