name: Jupyter Book Build as Test Suite
env:
  POPTUS_PKG:      ${{ github.workspace }}/poptus_pypkg
  GH_ACTIONS_PATH: ${{ github.workspace }}/.github/workflows
  BOOK_HTML_BUILD: ${{ github.workspace }}/book/_build/html
on:
  # Only execute on PRs into main under the assumption that the publish_book
  # action builds the book and publishes it on pushes to main.
  pull_request:
    branches: main

jobs:
  # Prefer using the latest Python version supported by the package
  #
  # Since notebooks contain regular and sanity checks, this action not only
  # confirms that the book is building correctly, but also
  # * that notebooks are generating correct content and therefore
  # * that our "Jupyter book test suite" passed.
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.14
    - name: Setup Python with tox
      run: $GH_ACTIONS_PATH/setup_tox_github_action.sh ${{ runner.os }}
    - name: Build Jupyter book
      run: |
        pushd $POPTUS_PKG
        tox -r -e book
        popd
    - name: Archive examples Jupyter book 
      uses: actions/upload-pages-artifact@v3
      with:
        path: ${{ env.BOOK_HTML_BUILD}}
